library(tidyverse)
library(dplyr)
library(purrr)
library(readr)
library(ggplot2)
library(leaps)
library(lmtest)
library(randomForest)
library(glmnet)
library(MASS)
library(car)
library(ISLR)
library(perturb)
library(tree)
library(caret) 
library(stringr)
library(lubridate)
library(tidytext)
library(scales)
library(readxl)
library(shiny)
library(readxl)
library(broom)
library(reshape)
library(leaflet)
library(plotly)
library(devtools)
library(usethis)
library(keyring)
library(alphavantager)
library(twitteR)


# John Hopkins COVID19 DATA:
# https://github.com/CSSEGISandData/COVID-19
# https://github.com/CSSEGISandData/COVID-19.git

key_set("key")
key_set("secret")
key_set("atoken")
key_set("asecret")

key <- key_get("key")
secret <- key_get("secret")
atoken <- key_get("atoken")
asecret <- key_get("asecret")

setup_twitter_oauth(key, secret, atoken, asecret)
